- Makefile
- README.md
- ci/azure-pipelines.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> ci: update vm image

- go.mod
- go.sum
- scripts/build_plugins.sh
- test/bddtests/go.mod
- test/bddtests/go.sum
> fix: Ensure plugin build works on Mac and Linux

- test/bddtests/bddtests_test.go
- test/bddtests/fabriccli_steps.go
- test/bddtests/go.mod
- test/bddtests/go.sum
Related to trustbloc/fabric-peer-test-common#41
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
> chore: Update Fabric test common and godog dependency version

- cmd/ledgerconfig/common/config.go
- cmd/ledgerconfig/updatecmd/configpreprocessor.go
- go.mod
- go.sum
- scripts/build_plugins.sh
> chore: Added field 'Tags' to the config value

- cmd/file/uploadcmd/uploadcmd.go
- cmd/file/uploadcmd/uploadcmd_test.go
> fix: File upload doesn't allow nested paths

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/createidxcmd/createidxcmd_test.go
- cmd/file/model/model.go
- cmd/file/uploadcmd/uploadcmd.go
- cmd/file/uploadcmd/uploadcmd_test.go
- test/bddtests/fixtures/.env
> chore: Update file command to work with new file index structure

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/createidxcmd/createidxcmd_test.go
- cmd/file/model/model.go
- cmd/file/uploadcmd/uploadcmd.go
- cmd/file/uploadcmd/uploadcmd_test.go
- go.mod
- go.sum
- test/bddtests/features/file.feature
- test/bddtests/fixtures/.env
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
> chore: update sidetree-core-go revision

- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/fileidx-sidetree-config.json
- test/bddtests/fixtures/config/fabric/org1-config.json
- test/bddtests/fixtures/config/fabric/org2-config.json
- test/bddtests/fixtures/config/fabric/sidetree-config.json
Updated config using the new sidetree handler config format.
closes #62
> chore: Update to latest sidetree-fabric

- Makefile
- go.mod
- go.sum
- scripts/build_plugins.sh
- test/bddtests/fixtures/.env
- test/bddtests/go.mod
- test/bddtests/go.sum
> chore: Release 0.1.3

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/createidxcmd/createidxcmd_test.go
- cmd/file/uploadcmd/uploadcmd.go
- cmd/file/uploadcmd/uploadcmd_test.go
- go.mod
- go.sum
- scripts/check_lint.sh
- test/bddtests/features/file.feature
- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json
Update sidetree-core:
- send recovery and update commitment values in create request
- send public update key and  update commitment in update request
- configuration changes
Closes #71
> chore: update sidetree-core

- cmd/ledgerconfig/deletecmd/deletecmd.go
- cmd/ledgerconfig/fileidxupdatecmd/fileidxupdatecmd.go
- cmd/ledgerconfig/updatecmd/updatecmd.go
Added retries to ledger config update/delete and file index update.
closes #82
> fix: Add retries to SDK execute

- go.mod
- go.sum
- test/bddtests/features/file.feature
- test/bddtests/features/ledgerconfig.feature
- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json
- test/bddtests/fixtures/fabric/config/configtx.yaml
- update to latest sidetree-core and sidetree-fabric
Closes #84
> chore: update to latest sidetree-core and sidetree-fabric

- go.mod
- go.sum
- scripts/build_plugins.sh
- test/bddtests/fixtures/.env
- test/bddtests/go.mod
- test/bddtests/go.sum
> chore: Bump TrustBloc components to v0.1.4

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/uploadcmd/uploadcmd.go
- go.mod
- go.sum
- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json
Update to latest sidetree-core, sidetree-fabric
Closes #90
> chore: Update to latest sidetree-core, sidetree-fabric

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/uploadcmd/uploadcmd.go
- go.mod
- go.sum
- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json
Update sidetree-core lib, sidetree-fabric image
Closes #97
> chore: update sidetree-core, sidetree-fabric

- cmd/file/createidxcmd/createidxcmd.go
- cmd/file/uploadcmd/uploadcmd.go
- go.mod
- go.sum
- test/bddtests/fixtures/.env
- test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json
Update to latest sidetree-core
Closes #101
> chore: update sidetree-core (hashAlgorithm removed)

- go.mod
- go.sum
- scripts/build_plugins.sh
> chore: Release 0.1.5

- cmd/file/uploadcmd/uploadcmd.go
- cmd/file/uploadcmd/uploadcmd_test.go
> chore: Add file name to error message in upload command

- README.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> chore: rename master branch to main

- scripts/build_plugins.sh
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
> fix: add missing newline in sed replace
